using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITIEntities
{
    public class Student
    {
        // ID is the primary key and is auto generated by the database (Identity)
        public int ID { get; set; }
        [StringLength(50), Required]
        public string Name { get; set; }
        public int Age { get; set; }

        [ForeignKey(nameof(Department))]
        public int Deptno { get; set; }

        // Navigation property to Department
        public virtual Department Department { get; set; }

        public virtual List <StudentCourse> StudentCourses { get; set; }

    }
}
